@startuml

title classic message posted (with sentiments)

-> rtm : new message
rtm -> slacker : message
slacker -> bot : process_message

bot -> sentimental : analysis
sentimental --> bot : Sentiments
bot -> database : set
bot -> slacker : post
<- slacker : post

@enduml
