@startuml

title ask for the users list with sentiments (command)

-> rtm : new message
rtm -> slacker : message
slacker -> bot : process_message

bot -> database : all
database --> bot : List
bot -> slacker : post
<- slacker : post

@enduml
